services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "81:80"
    networks:
      - shop_app
    depends_on:
      - database

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-marcel}
      MYSQL_USER: ${MYSQL_USER:-marcel}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-marcel1}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-marcel1}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - skeleton-shop-api-data:/var/lib/mysql:rw
    networks:
      - shop_app
  ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  skeleton-shop-api-data:
  ###< doctrine/doctrine-bundle ###

networks:
  shop_app:
