version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "81:80"
    networks:
      - apilo_service

networks:
  apilo_service: